
domain = "http://23.225.92.244:12345/tiankong.php"

[search]
url = "/v6/search?token=&csrf=itrwDUz171Uho47GsVx5Og%2F%2BY8AiHJfKmPBI%2FiSBqp5briAaYuA84D8qjhcdwErsMcxVJ0a8bI9F8R9BnnJNp4IDL3N3W5jJBPTEzLXsz6fcm8zzvxgYkG5DrirRgejCANrujM5cPo0YVEljVuUrECb2DukvO%2F3oYIij5mMuNF0%3D"

[home]
# banner
banner_url = "/v6/advert?position=2&pkid=com.maitian.baohu&token=&csrf=WObpyaoSv%2FyeMhF53v40oNiwn3GxPC2E6WMMf8DKeLcRiypJSQk0LyoENBJ2mz%2FkHFMGPT%2Byfsp0Uroypa%2FoepkoG35bBoHqI%2FZmxmImzXfU4c2VW%2BJ%2BL43c80mKX5ScG%2Ffj5kLvL%2B5hbYwRS3ualIB4pJGzDM9NsCd4tTMXabE%3D"
# 推荐
recommend_url = "/v6/index_video?token=&csrf=DLC7rYD06SP%2B%2FFOh%2FhZ9zbqrK1hoxw1%2F8OpSYoxg9Ln4GuHLtmta2G38UkLhx6Nf3%2BCmZ%2FLG2OiG2LlK%2BA4HKfG%2FCKJXq3PUB2SrVOcnGQl4kV2d3NVC9B2w%2F3X8shtncslqv4L9FyZTGFyoXW3duPNNUqFFjB9X2DMSxIbPJkE%3D"
# 剧集 tid = 20
drama_series_url = "/v6/video?tid=20&token=&csrf=rwkT21B0QYuoUS43G2yp6a1IxprLJ%2FSItzpWpF1fRySGtvnzxoGjpudz1YdEbWNntL8U1ZvMicMxr%2B7iESs5WWxbmEWPcJpIvi7xMlyi0sL2SVl4YuPKpb%2FA6I%2FEPwMLUJdMai9W6IQ%2BSJnO2gA500JDbMRqabrxgCoy8qQ09MI%3D"
# 电影 tid = 21
movie_url = "/v6/video?tid=21&token=&csrf=dZzpbNGpE2xhYue6jhA%2Bod2%2BT5mRpfY2w%2B5F4RPiq2V4vMU7fa%2F2tGdqZaLXr5caTZKYn0uCanhGuAZ8NZuQbosGDcjjiCzioGJQqmBMWNaPeH5RlxuOJW1Ty3ryz75tWG%2FGx2OOCuDm0NOHESIIHZ0ShdRKRGZAzLntetIlQyY%3D"
# 动漫 tid = 22
cartoon_url = "/v6/video?tid=22&token=&csrf=Em6Ed9WwaC2uMprfhHv4BBIZhzwCKuWIwpar2OFWxYETUQRZUWi6fLimyv7AiyGOgHNq0817Ju%2F7HzSXbJAB8u70ZGbrkk8LyoU4EZ%2FUva1ciNwOauKhOa9KntiY66bwqxCJdyo1V9KoN2LtrNz5ALiljtjiAVqSap%2BFY2Gby%2Fw%3D"
# 综艺 tid = 23
variety_url = "/v6/video?tid=23&token=&csrf=Em6Ed9WwaC2uMprfhHv4BBIZhzwCKuWIwpar2OFWxYETUQRZUWi6fLimyv7AiyGOgHNq0817Ju%2F7HzSXbJAB8u70ZGbrkk8LyoU4EZ%2FUva1ciNwOauKhOa9KntiY66bwqxCJdyo1V9KoN2LtrNz5ALiljtjiAVqSap%2BFY2Gby%2Fw%3D"
# 少儿 tid = 24
children_url = "/v6/video?tid=24&token=&csrf=Em6Ed9WwaC2uMprfhHv4BBIZhzwCKuWIwpar2OFWxYETUQRZUWi6fLimyv7AiyGOgHNq0817Ju%2F7HzSXbJAB8u70ZGbrkk8LyoU4EZ%2FUva1ciNwOauKhOa9KntiY66bwqxCJdyo1V9KoN2LtrNz5ALiljtjiAVqSap%2BFY2Gby%2Fw%3D"
# 记录 tid = 25
record_url = "/v6/video?tid=26&token=&csrf=Em6Ed9WwaC2uMprfhHv4BBIZhzwCKuWIwpar2OFWxYETUQRZUWi6fLimyv7AiyGOgHNq0817Ju%2F7HzSXbJAB8u70ZGbrkk8LyoU4EZ%2FUva1ciNwOauKhOa9KntiY66bwqxCJdyo1V9KoN2LtrNz5ALiljtjiAVqSap%2BFY2Gby%2Fw%3D"

[detail]
url = "/v6/video_detail?id=130432&ck=QFtjIVPi6XPrBc0PeE%2FJztZCeHM3a0uEenmnRuy4nl%2BrKxcwqxEk0hIaCcUZS1EfRHm7Z804jmI32TM%2BninJzqbtajsh6902eK%2BSgHkTh9SxGFYwQjGf%2BA3sDaU6xZOI7hHIL8gx084Cwu4iUixhAfOHaZ0CQWGHqYpJJX1t7fM%3D&pkid=com.maitian.baohu&token=&csrf=FbNvuMrdjDQyRL%2B%2F6ZL0eU8d25f%2BRHYjwmi58z0FMhrnuY3JTXKKkgikB3%2F6oxP6vmeSZsu%2BpAiOv6f1p8hGGAzqsPLyWaV0c52lTYFYXLVZOw6IA5Zc7JdbZqzs9GoefsJNUMw3REgGk1MxMsqvecXYLz5jDBiPo43IvKm%2FKU0%3D"
guess_url = "/v6/video_prefer?tid=20&vid=130432&token=&csrf=GrGsNATWobdY%2Fmzvs2%2BV3vIb%2Bg2ew1hX1OxrqH17eooqnGtW2mljiM%2BYrNmKEQyhhGXUp2S4%2BOHvxnFXs33BKfNDBcd74VA7HLoDygXX7c9C571OXdDqn9k2PoH8yOMUSMIDqijXjkV175DXQ%2BMz2qSd08UIwO%2FyqVvnZNy5u5s%3D"

[rank]
url = "/v6/rank_video_list?token=&csrf=NRIzPeROcHJjI2k%2BYlqD1UzzL9CBPFCGjwgjOlIHo2xmPaZEgJ2AgmLsrUNeriGmZ5OTsYqfGB6YuAVNcF%2FaQ1FX54Iegtj5hLnAeyq%2FgWB7soYWsbVy5y0V1wLoXE8eY%2FBclUoqktat3ULmfA8xm4R8CWjnEWjIOhzZaTft9%2Bk%3D"